app/Http/routes.php
<?php
Route::group(['middleware' => 'auth'], function () {


    Route::get('/','InvoiceController@htmlDisplay');

    Route::get('invoices/pending','InvoiceController@pending');

    Route::get('clients/{id}/details','ClientController@details',compact('id'));
    Route::get('invoices/{id}/details','InvoiceController@details',compact('id'));

    Route::get('invoices/{id}/modify','InvoiceController@modify',compact('id'));

    Route::post('invoices/{id}/update2','InvoiceController@update2',compact('id'))->name('invoices.update2');

    Route::resource('clients', 'ClientController');

    Route::get('clients/{id}/delete', [
        'as' => 'clients.delete',
        'uses' => 'ClientController@destroy',
    ]);

    Route::resource('invoices', 'InvoiceController');

    Route::get('invoices/{id}/delete', [
        'as' => 'invoices.delete',
        'uses' => 'InvoiceController@destroy',
    ]);

    Route::resource('items', 'ItemController');

    Route::get('items/{id}/delete', [
        'as' => 'items.delete',
        'uses' => 'ItemController@destroy',
    ]);

    Route::get('htmlinvoice','InvoiceController@htmlDisplay');

    Route::post('dieDump','ItemController@dieDump');

    Route::post('email','InvoiceController@sendDefaulterEmail');

    Route::post('returnClient','ItemController@returnClient');

    Route::post('submitComments','ItemController@submitComments');

    Route::get('invoices/{id}/see', ['as' => 'see', 'uses' => 'InvoiceController@see']);

    Route::get('invoice/{id}/sendReminderEmail', ['as' => 'sendReminderEmail', 'uses' => 'InvoiceController@sendReminderEmail']);

    Route::get('invoice/{id}/paymentReceived', ['as' => 'paymentReceived', 'uses' => 'InvoiceController@paymentReceived']);


});

Route::get('auth/login', 'Auth\AuthController@getLogin');
Route::post('auth/login', 'Auth\AuthController@postLogin');
Route::get('auth/logout', 'Auth\AuthController@getLogout');

Route::resource('taxes', 'TaxController');

Route::get('taxes/{id}/delete', [
    'as' => 'taxes.delete',
    'uses' => 'TaxController@destroy',
]);

resources/views/_bill-to.blade.php
	<div class="bluebg" style="width:100%;">BILL TO: <?php $clients = App\Models\Client::all(); ?>
      <span style="float:right" class="no-print">Select Client </span>
      <select id="client-name-dropdown" name="client_ID" class="form-control no-print">
      <option disabled="disabled" selected="selected">Select Client</option>
      @foreach($clients as $client)
      	<option value={{ $client->id }}>{{$client->name}}</option>
      @endforeach
      </select>
    </div>
	

resources/views/_cssinclude.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>invoice</title>
    {{-- <link href="https://fonts.googleapis.com/css?family=Lato:100" rel="stylesheet" type="text/css"> --}}
    <link href="/css/_bootstrap.css" rel="stylesheet">
    {{-- <link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css"> --}}
    <style>
    .container{
        padding: 3%;
    }
    .billing-details{
        height: 350px;
        /*padding-top: 3%;*/
    }
    .lcol{
        width:30%;
        /*position: absolute;*/
        float: left;
        padding-left: 3%;

    }
    .rcol{
        width:30%;
        /*position: absolute;*/
        float: left;        
        margin-left: 15px;
        -webkit-print-color-adjust:exact;
    }
    .ccol{
        width:30%;
        margin-top: 5%;
        /*position: absolute;*/
        float: left;
    }
    .invoice-details{
        float: right;

    }
    .job-number{
        font-weight: bold;
    }
    
    
    .height {
        min-height: 200px;
    }


    .custom-tab1>tbody>tr>td {
        padding: 5px;
        vertical-align: middle;
        border: none;
    }
    .postscript{
        margin-top: 50px;

    }
    .bluebg{
        background-color: #3B4E87;
        color:#fff;
        font-weight: bold;
    }
    .table {
        margin: 0;
        border: 2px solid #ddd;
    }
    @media print{
        .no-print{
            display: none;
        }
        .print-margin-left{

        }
    }
    .font-bold{
        font-weight:bold;
    }
    .admin-bar{
        background-color: #E4E8F3;
        height: 40px;
        font-size: 17px;
    }
    .admin-bar div{
        padding: 20px;
    }
    .admin-bar div, .admin-bar div span, .admin-bar div select{
        display: inline;
    }
    .admin-bar div select{
        width:inherit;
    }
    </style>
</head>

resources/views/_jsinclude.blade.php
<script src="/js/jquery-2.1.4.js"></script>
<script src="/js/jquery-1.11.1.min.js"></script>
<script src="/js/bootstrap.js"></script>
<script>

var tax = $('#hidden-tax-percent').val();
var i=parseInt($('#hidden-line-item-count').val());
var newItems = 0;
console.log(i);
var subtotal=0;
$('document').ready(function(){
	$('input:radio[name=tax-applicable]').click(function() {
	  var val = $('input:radio[name=tax-applicable]:checked').val();
	  tax = val=='yes'? tax : 0;
	  console.log(val);
	  console.log(tax);
	});
	
	$('#add-lineitem').click(function(){
		i+=1;
		$('<tr class="lineitem'+i+'"> \
				<td id="lineitems[' + i + '][description]" style="border-right: 2px solid #ddd;  padding:0; height:40px;"><input type="text" name="lineitems['+i+'][description]" style="width:100%; height:100%; border:none;"></td> \
				<td class="amount-box" id="lineitems[' + i + '][amount]" style="text-align:right; padding:0; height:40px;"><input type="text" id="amount'+i+'" name="lineitems['+i+'][amount]" style="width:100%; height:100%; border:none; text-align:right;" value="0" class="amount"></td> \
			</tr>').insertAfter('.lineitem'+(i-1)); 
		newItems+=1;
		$('#new-line-item-count').val(newItems);
	});
	$('#client-name-dropdown').change(function(){
		$.post("/returnClient",{ "id": $(this).val(), "_token": $("[name='_token']").val() }, function(data){ 
		$("#client-name").html(data.name);
		$("#client-address").html(data.address);
		$("#client-id").html(data.id);	
		$('#hidden-client-id').val(data.id);
		});
	});

	var stotal = 0;
	$('tbody').focusout(function(){
		
		$('.amount').each(function(){
			stotal+=parseInt($(this).val());
		});
		$('#subtotal').text(stotal);
		$('#service-tax').text(parseInt(tax/100*stotal));
		$('#total').text(parseInt(stotal+(tax/100*stotal)));
		console.log(stotal);
		stotal=0;
	});
	console.log(stotal);

	
	// function AppViewModel(){
	// 	this.amount = ko.observable("0");
	// }
	// ko.applyBindings(new AppViewModel());
	
});
</script>
</html>

resources/views/_our-address.blade.php
<h1>it's alive</h1>
	Technology, Design, Innovation.<br/>
	210,2B Ashirwad,Seven Bungalows<br/>
	Versova, Mumbai - 400061.<br/>
	sales@itsalive.in<br/>
	9820860909 / 9769595468<br/><br/>

resources/views/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<title>Laravel</title>

	<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css" rel="stylesheet">

	<!-- Fonts -->
	<link href='//fonts.googleapis.com/css?family=Roboto:400,300' rel='stylesheet' type='text/css'>

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
	<!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
	<!--[if lt IE 9]>
		<script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
		<script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
	<![endif]-->
</head>
<body>
	<nav class="navbar navbar-default">
		<div class="container-fluid">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar">
					<span class="sr-only">Toggle Navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand" href="#">Laravel</a>
			</div>

			<div class="collapse navbar-collapse" id="navbar">
				<ul class="nav navbar-nav">
					<li><a href="{{ url('/') }}">Welcome</a></li>
				</ul>

				<ul class="nav navbar-nav navbar-right">
					@if(auth()->guest())
						@if(!Request::is('auth/login'))
							<li><a href="{{ url('/auth/login') }}">Login</a></li>
						@endif
						@if(!Request::is('auth/register'))
							<li><a href="{{ url('/auth/register') }}">Register</a></li>
						@endif
					@else
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">{{ auth()->user()->name }} <span class="caret"></span></a>
							<ul class="dropdown-menu" role="menu">
								<li><a href="{{ url('/auth/logout') }}">Logout</a></li>
							</ul>
						</li>
					@endif
				</ul>
			</div>
		</div>
	</nav>

	@yield('content')

	<!-- Scripts -->
	<script src="//cdnjs.cloudflare.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
	<script src="//cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.5/js/bootstrap.min.js"></script>
</body>
</html>

resources/views/email.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>invoice</title>
</head>
<body>
hi
@foreach($defaultedInvoices as $defaultedInvoice)
	ID : {{ $defaultedInvoice->id }}
	Invoiced to : {{$defaultedInvoice->client->name}}<br/>
@endforeach
</body>
</html>

resources/views/home.blade.php
@extends('app')

@section('content')
<div class="container">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<div class="panel panel-default">
				<div class="panel-heading">Home</div>

				<div class="panel-body">
					You are logged in!
				</div>
			</div>
		</div>
	</div>
</div>
@endsection

resources/views/inv.blade.php
@include('_cssinclude')
<body>
@if($new == 1)
{!! Form::open(array('action' => 'ItemController@dieDump', 'class' => 'form-horizontal')) !!}

@else
{!! Form::model($invoice, ['route' => ['invoices.update', $invoice->id], 'method' => 'patch']) !!}

@endif
<div class="admin-bar no-print text-center">	
<div>Title : <input type="text" name="title" id="title" value="{{$title}}"></div>
<div>Tax applicable? <input type="radio" name="taxes_applicable" value="1" {{$taxes_applicable ? 'checked' : ''}}>Yes<input type="radio" name="taxes_applicable" value="0" {{$taxes_applicable ? '' : 'checked'}}>No</div>
<div>Bill To: <?php $clients = App\Models\Client::all(); ?>
      <select id="client-name-dropdown" class="form-control no-print">
      <option disabled="disabled" selected="selected">Select Client</option>
      @foreach($clients as $client)
      	<option value={{ $client->id }}>{{$client->name}}</option>
      @endforeach
      </select>
</div>
<input type="hidden" id="hidden-client-id" name="client_ID" value=""> <!-- check why i haven't used name in select field" -->
<div>Recurring? <input type="radio" name="recurring" value="1" {{$recurring ? 'checked' : ''}}>Yes<input type="radio" name="recurring" value="0" {{$recurring ? '' : 'checked'}}>No</div>
</div>
<div class="container">

<div class="billing-details">
	<div class="lcol">
	@include('_our-address')

	
	<span id="client-name">{!! $client->name !!}</span><br/>
	<span id="client-address">{!! $client->address !!}</span><br/>
	<span id="client-phno">{!! $client->phno !!}</span><br/>
	
	<input type="hidden" name="id" value="{{$invoice_number}}">
	</div>
	<div class="ccol">
	sales@itsalive.in<br/>
	Pan Card No.: AADFI2139R<br/>
	ST No. : AADFI2139RSD002<br/>
	ST Category: Information Technology Software &amp; Design Service<br/>
	
	</div>
	<div class="rcol">
	<span style="color: #6666CC; font-size:40px; float:right;">INVOICE</span><br/><br/><br/>
	<div class="row"><span class="font-bold">DATE: </span><span class="invoice-details">{{ $date }}</span> </div>
	<div class="row"><span class="font-bold">INVOICE #: </span><span id="invoice-number" class="invoice-details">{{ $invoice_number }}</span> </div>
	<div class="row"><span class="font-bold">Customer ID:  </span><span id="client-id" class="invoice-details"> {{ $invoice->client_ID }}</span> </div>

	
	</div>

</div>
<div class="clearfix"></div>
<div class="job-number text-center print-margin-left"><input type="text" id="job-number" value="{{$job_number}}" name="job_number"></div><br/>


<input type="hidden" value="{{$tax}}" id="hidden-tax-percent">
<div class="job-description">
	<table id="main-table" class="table">
		<thead>
			<tr class="bluebg">
				<th width="90%" style="border-right: 2px solid #ddd; text-align:center">DESCRIPTION <div id="add-lineitem" style="float:right; height:20px;"><img src="/images/plus_sign.png" style="max-height:100%; cursor:pointer;" class="no-print"></div></th>
				<th width="10%" style="text-align:center;">AMOUNT</th>
			</tr>
		</thead>
		<tbody>
		
		@if(isset($line_item_count))
		<input type="hidden" value="{{$line_item_count}}" id="hidden-line-item-count">
		<input type="hidden" name="new_line_item_count" id="new-line-item-count" value="0">
		@for($i = 1; $i<=$line_item_count; $i++)
			<tr class="lineitem{{$i}}">
				<td name="lineitems[{{$i}}][description]" style="border-right: 2px solid #ddd; padding:0; height:40px;"><input type="text" name="lineitems[{{$i}}][description]" style="width:100%; height:100%; border:none;" value="{{$line_items[$i-1]['description']}}"></td>

				<td name="lineitems[{{$i}}][amount]" style="text-align:right; padding:0; height:40px;"><input type="text" class="amount" id="{{$line_items[$i-1]->id}}" name="lineitems[{{$i}}][amount]" style="text-align:right; height:100%; border:none; width:100%;" value="{{$line_items[$i-1]['amount']}}"></td>
				
			</tr>
			<input type="hidden" name="lineitem_ids[{{$i}}]" value="{{$line_items[$i-1]->id}}">

		@endfor
		
		@else
			<input type="hidden" value="1" id="hidden-line-item-count">
			<tr class="lineitem1">
				<td name="lineitems[1][description]" style="border-right: 2px solid #ddd; padding:0; height:40px;"><input type="text" name="lineitems[1][description]" style="width:100%; height:100%; border:none;"></td>
				<td name="lineitems[1][amount]" style="text-align:right; padding:0; height:40px;"><input type="text" class="amount" id="amount1" name="lineitems[1][amount]" style="text-align:right; height:100%; border:none; width:100%;" value="0"></td>
			</tr>

		@endif
	
		
			<tr>
				<td colspan="2" style="padding:0;"><table width="100%" style="border:none;" class="table custom-tab1">
					<thead>
						<tr style="border-top: 1px solid #ddd;">
							<th width="70%" style="border-right: 2px solid #ddd; background-color:#C0C0C0;">OTHER COMMENTS</th>
							<th width="20%" style="border-right: 2px solid #ddd;">SUBTOTAL</th>
							<th id="subtotal" width="10%" style="text-align:right; background-color: #E4E8F3;">{{ 0 }}</th>
						</tr>
					</thead>
					<tbody>
                          <tr>
                          @if($new==1)
                            <td rowspan="2" style="border-right: 2px solid #ddd; padding: 0px;" contenteditable="true"><textarea name="comments" id="other-comments" style="border:none; width:100%; height:100px; text-align:left;">1) Total payment due on 1st September, 2015.
2) Please include the invoice number on your cheque.
3) Make all cheques payable to "It's Alive".</textarea></td>
						   @else
							<td rowspan="2" style="border-right: 2px solid #ddd; padding: 0px;" contenteditable="true"><textarea name="comments" id="other-comments" style="border:none; width:100%; height:100px; text-align:left;">{{$comments}}</textarea></td>
						   @endif
                            <td style="border-right: 2px solid #ddd;">Service Tax ({{$tax}}%)</td>
                            <td id="service-tax" style="text-align:right;">0.00</td>
                          </tr>
                          <tr>
                            <td style="border-right: 2px solid #ddd; border-top: 1px solid #ddd;">TOTAL</td>
                            <td id="total" style="text-align:right; border-top: 1px solid #ddd;">0.00</td>
                          </tr>
                        </tbody>
				</table></td>
			</tr>
		</tbody>
	</table>
	 {!! Form::submit('Save', array('class' => 'submit-form no-print btn btn-default form-control')) !!}
{!! Form::close() !!}
</div>

<div class="postscript text-center">
If you have any questions about this invoice, please contact <br/>
Paramveer Bhatti, +919820860909, paramveer@itsalive.in<br/><br/>

<span style="font-weight:bold; font-size:20px;">Thank you for your business!</span>
</div>

</div>
</body>
@include('_jsinclude')

resources/views/layout.blade.php
<!DOCTYPE html>
<html>
<head>
   <title>invoice</title>
@include('_cssinclude')
</head>

resources/views/pending.blade.php
@extends('app')
@section('content')
<div class="container">
    <div class="row">
        <h1 class="pull-left">Details</h1>
    </div>
    <div class="row">
        <table class="table">
            <thead>
                <th>Invoice no.</th>
                <th>Issued to</th>
                <th>Due Date</th>
                <th>Title</th>
                <th>Amount</th>
                <th>Action</th>
            </thead>
            <tbody>
                @foreach($invoices as $invoice)
                <?php
                $client = \App\Models\Client::find($invoice->client_ID);
                $due_date = \Carbon\Carbon::parse($invoice->date)->format('d/m/Y');
                ?>
                <tr>
                    <td>{!! $invoice->id !!}</td>
                    <td>{!! $client->name !!}</td>
                    <td>{!! $due_date !!}</td>
                    <td>{!! $invoice->title !!}</td>
                    <td>{!! $invoice->items->sum('amount') !!}</td>
                    <td>
                        <a href="{!! route('invoices.edit', [$invoice->id]) !!}"><i class="glyphicon glyphicon-edit"></i></a>
                        <a><i class="glyphicon glyphicon-euro" data-toggle="modal" data-target="#myModal"></i></a>
                        <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
                            <div class="modal-dialog" role="document">
                                <div class="modal-content">
                                    <div class="modal-header">
                                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                                        <h4 class="modal-title" id="myModalLabel">Modal title</h4>
                                    </div>
                                    <div class="modal-body">
                                        ...
                                    </div>
                                    <div class="modal-footer">
                                        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                                        <button type="button" class="btn btn-primary">Save changes</button>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <a href="{{route('sendReminderEmail',['id' => $invoice->id])}}" onclick="return confirm('Are you sure you want to send a reminder email?')"><i class="glyphicon glyphicon-envelope"></i></a>
                        <a href="{!! route('invoices.delete', [$invoice->id]) !!}" onclick="return confirm('Are you sure you want to delete this Invoice?')"><i class="glyphicon glyphicon-remove"></i></a>
                    </td>
                </tr>
                @endforeach
            </tbody>
        </table>
    </div>
</div>
@endsection

resources/views/reminderEmail.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Your reminder</title>
</head>
<body>
	
</body>
</html>

resources/views/see.blade.php
@include('_cssinclude')
<body>
<div class="container">
<div class="billing-details">
	<div class="lcol">
	@include('_our-address')

	<span id="client-name">{!! $client->name !!}</span><br/>
	<span id="client-address">{!! $client->address !!}</span><br/>
	<span id="client-phno">{!! $client->phno !!}</span><br/>
	</div>
	<div class="ccol">
	sales@itsalive.in<br/>
	Pan Card No.: AADFI2139R<br/>
	ST No. : AADFI2139RSD002<br/>
	ST Category: Information Technology Software &amp; Design Service<br/>
	</div>
	<div class="rcol">
	<span style="color: #6666CC; font-size:40px; float:right;">INVOICE</span><br/><br/><br/>
	<div class="row"><span class="font-bold">DATE: </span><span class="invoice-details">{{ $date }}</span> </div>
	<div class="row"><span class="font-bold">INVOICE #: </span><span id="invoice-number" class="invoice-details">{{ $invoice_number }}</span> </div>
	<div class="row"><span class="font-bold">Customer ID:  </span><span id="client-id" class="invoice-details"> {{ $invoice->client_ID }}</span> </div>
	</div>
</div>
<div class="job-number text-center print-margin-left">{{$job_number}}</div><br/>
<div class="job-description">
	<table id="main-table" class="table">
		<thead>
			<tr class="bluebg">
				<th width="90%" style="border-right: 2px solid #ddd; text-align:center">DESCRIPTION <div id="add-lineitem" style="float:right; height:20px;"></div></th>
				<th width="10%" style="text-align:center;">AMOUNT</th>
			</tr>
		</thead>
		<tbody>
			@for($i = 1; $i<=$line_item_count; $i++)
				<tr class="lineitem1">
					<td name="lineitems[{{$i}}][description]" style="border-right: 2px solid #ddd; padding:0; height:40px; margin-top:2px;">{{$line_items[$i-1]['description']}}</td>

					<td name="lineitems[{{$i}}][amount]" style="text-align:right; padding:0; height:40px;">{{$line_items[$i-1]['amount']}}</td>
					
				</tr>
			@endfor
			<tr>
				<td colspan="2" style="padding:0;"><table width="100%" style="border:none;" class="table custom-tab1">
					<thead>
						<tr style="border-top: 1px solid #ddd;">
							<th width="70%" style="border-right: 2px solid #ddd; background-color:#C0C0C0;">OTHER COMMENTS</th>
							<th width="20%" style="border-right: 2px solid #ddd;">SUBTOTAL</th>
							<th id="subtotal" width="10%" style="text-align:right; background-color: #E4E8F3;">{{ $amount }}</th>
						</tr>
					</thead>
					<tbody>
                          <tr>
                            <td rowspan="2" style="border-right: 2px solid #ddd; padding: 0px;" contenteditable="true"><textarea name="comments" id="other-comments" style="border:none; width:100%; height:100px; text-align:left;">{{$comments}}</textarea></td>
                            <td style="border-right: 2px solid #ddd;">Service Tax ({{$tax}}%)</td>
                            <td id="service-tax" style="text-align:right;"><?php $stax = round($tax/100*$amount,0); echo $stax; ?></td>
                          </tr>
                          <tr>
                            <td style="border-right: 2px solid #ddd; border-top: 1px solid #ddd;">TOTAL</td>
                            <td id="total" style="text-align:right; border-top: 1px solid #ddd;">{{$stax+$amount}}</td>
                          </tr>
                        </tbody>
				</table></td>
			</tr>
			</tbody>
	</table>
</div>
<div class="postscript text-center">
If you have any questions about this invoice, please contact <br/>
Paramveer Bhatti, +919820860909, paramveer@itsalive.in<br/><br/>

<span style="font-weight:bold; font-size:20px;">Thank you for your business!</span>
</div>

</div>
</body>
</html>